package:
  name: fc-virus
  version: "1.0.0"

source:
  git_url: https://github.com/qdu-bioinfo/FC-Virus.git
  git_tag: master

requirements:
  run:
    - c++

about:
  home: https://github.com/qdu-bioinfo/FC-Virus
  license: MIT
  summary: "Accurate Assembly of Full-length Consensus for Viral Quasispecies"
